baseurl: "/" # the name of your github repo
url: "https://www.bagusmw.me"

# site information used in page title, meta data etc.
title: "bagusmw.me"
description: Bagus Muhammad Wijaksono's Personal Website

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Bagus Muhammad Wijaksono
author-bio: Software Developer / DevOps Engineer # change to false to hide
author-image: 86aa9f24121cd5971928cf1533606073733469256f74d19e0a6caa7b4cdb66a1.webp

show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

github: https://github.com/baguswjksn
linkedin: https://linkedin.com/in/bgswjk
email: baguswjksn@proton.me

plugins:
    - jekyll-seo-tag
